/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authedRouteRouteImport } from './routes/(authed)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authedDashboardIndexRouteImport } from './routes/(authed)/dashboard/index'
import { Route as authedDashboardProjectIdRouteImport } from './routes/(authed)/dashboard/$projectId'

const authedRouteRoute = authedRouteRouteImport.update({
  id: '/(authed)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authedDashboardIndexRoute = authedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => authedRouteRoute,
} as any)
const authedDashboardProjectIdRoute =
  authedDashboardProjectIdRouteImport.update({
    id: '/dashboard/$projectId',
    path: '/dashboard/$projectId',
    getParentRoute: () => authedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard/$projectId': typeof authedDashboardProjectIdRoute
  '/dashboard/': typeof authedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/$projectId': typeof authedDashboardProjectIdRoute
  '/dashboard': typeof authedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(authed)': typeof authedRouteRouteWithChildren
  '/(authed)/dashboard/$projectId': typeof authedDashboardProjectIdRoute
  '/(authed)/dashboard/': typeof authedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard/$projectId' | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard/$projectId' | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/(authed)'
    | '/(authed)/dashboard/$projectId'
    | '/(authed)/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authedRouteRoute: typeof authedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(authed)': {
      id: '/(authed)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authed)/dashboard/': {
      id: '/(authed)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof authedDashboardIndexRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/dashboard/$projectId': {
      id: '/(authed)/dashboard/$projectId'
      path: '/dashboard/$projectId'
      fullPath: '/dashboard/$projectId'
      preLoaderRoute: typeof authedDashboardProjectIdRouteImport
      parentRoute: typeof authedRouteRoute
    }
  }
}

interface authedRouteRouteChildren {
  authedDashboardProjectIdRoute: typeof authedDashboardProjectIdRoute
  authedDashboardIndexRoute: typeof authedDashboardIndexRoute
}

const authedRouteRouteChildren: authedRouteRouteChildren = {
  authedDashboardProjectIdRoute: authedDashboardProjectIdRoute,
  authedDashboardIndexRoute: authedDashboardIndexRoute,
}

const authedRouteRouteWithChildren = authedRouteRoute._addFileChildren(
  authedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authedRouteRoute: authedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
